### ISSUE TITLE
Mail Distribution

### ISSUE THREAD

**Issue by sjoblads** [DIT112-V21/group-17#10]
**As a manager I want to be able to distribute mail to users with the car so that I do not have to do it myself**

- Acceptance criteria:  There should be a function on the application which calls the car to send mail to a designated location.

**Comment by Eliflili** [comment]
It's out of scope. we don't need it.

**Comment by Leililou** [comment]
This is not an apropriate issue, we dont have a manager and user term is vague and it is not a simple fuctionality, that's the definition of the whole project impossible to link it to any specific feature
