### ISSUE TITLE
Autonomous mode

### ISSUE THREAD

**Issue by Leililou** [DIT112-V21/group-17#114]
## User story 8.1: Autonomous mode
As a car monitor I want the car to move forward and stop to deliver mails.
### Acceptance criteria

- [ ] The car should stop every 5 meters.
- [ ] The car should wait 30 seconds the time for the receiver picks up the mail.
- [ ] The control buttons should be disabled

**Comment by MaabMohammedali** [comment]
It assigned to someone and not deliver it on time
