### ISSUE TITLE
Final Group Report

### ISSUE THREAD

**Issue by MaabMohammedali** [DIT112-V21/group-17#118]
**The final group report should contain:**

**Group contributions**

An overall description of how each of the team members contributed to the system and the group-work
Do not forget to mention work that might not be version controlled as well as each member's GitHub username

**Post-mortem**

Evaluate and describe your group's work and product
What would you do differently?

**A group photo along with your names :)**

**Comment by Leililou** [comment]
I think it's better to have this one as a Milestone because we have many issues to tackle inside what do you think @MaabMohammedali @Eliflili @SvenHagenfors @sjoblads @guscuizi

**Comment by MaabMohammedali** [comment]
We have a milestone named  finalize the Project and I think we can link this issue and readme issue also to it because both issue related to the same thing which is finalize the project.

**Comment by Leililou** [comment]
Done and submitted :)
