### ISSUE TITLE
Finalize readme file

### ISSUE THREAD

**Issue by MaabMohammedali** [DIT112-V21/group-17#119]
**The project should have a high quality README.md file which contains:**

1. Explains "What? Why? How?" about the project
2. Illustrates the hardware and software architecture with text and/or diagrams
3. Instructs how to set up and get started with the project
4. Includes a link to a Youtube video with a demo of the full functionality of your project
5. Write a user manual
6. Write a "Get started" guide for developers

**Comment by MaabMohammedali** [comment]
We still need  to work on readme.file it is not done yet

**Comment by Leililou** [comment]
Done
