### ISSUE TITLE
Log-out

### ISSUE THREAD

**Issue by sjoblads** [DIT112-V21/group-17#12]
**As a user I want to be able to log out of the application so that others do not get access to my account**

- Acceptance criteria:  There should be a function on the application which allows the user to log out and returns them to the login page.

**Comment by Leililou** [comment]
To be considered in the future sprints

**Comment by Leililou** [comment]
this issue was started to be implemented (android side) but not finished and now is out of scope, due to lack of time and also because it's not a priority.
