### ISSUE TITLE
Car Movement

### ISSUE THREAD

**Issue by sjoblads** [DIT112-V21/group-17#13]
**As a manager I want the car to be able to move around carrying the mails in all directions in the usual terrain.**

- Acceptance criteria:  There should be functions which allow the manager to steer the car forward, backward, left and right.

**Comment by Leililou** [comment]
This also should be for the next sprints after having functional buttons linked to the arduino

**Comment by Leililou** [comment]
This issue has been changed after we reworked our user stories so it's not useful for our project. The issue that replaced it is car direction issue#24

**Comment by MaabMohammedali** [comment]
Fixing car movement

**Comment by MaabMohammedali** [comment]
Car Movement Fix
