### ISSUE TITLE
[DOCUMENTATION] Update the requirements of DeliRover App (Mailman version)

### ISSUE THREAD

**Issue by Leililou** [DIT112-V21/group-17#154]
### Description
Update the requirements of DeliRover App (Mailman version) milestone to match the existing functionalities
- Update the functional requirments
- Update the non functional requirments
- Add Assumptions
- Add scenarios
- Make sure to Link the requirments page to the corresponding milestone

**Comment by MaabMohammedali** [comment]
The explanation of mailman version is clear.
