### ISSUE TITLE
Delivery delay

### ISSUE THREAD

**Issue by Leililou** [DIT112-V21/group-17#29]
**User story #4.1: Delivery delay**
As a delivery receiver I want to know if there are any delays on the delivery so that I expect it.
**Acceptance criteria:**

- The mail man can send a notification to inform about the delay when the car is on manual control mode
- The car should send a notification if the delay is more than 2 minutes when it's on autonomous mode

**Comment by Leililou** [comment]
This issue is out of scope, this feature is useful in the autonomous mode that we won't be implementing because of lack of time.

**Comment by MaabMohammedali** [comment]
The mailman will send  a notifitcation to the reciever  once the car outside the door ,so the reciver do not need to calculate the delay time
