### ISSUE TITLE
Expect delivery notification

### ISSUE THREAD

**Issue by Leililou** [DIT112-V21/group-17#32]
User story 6.1: 
As a receiver I want to be notified when I have mail so that I expect it
Acceptance criteria:
The receiver should receive a notification via the app to expect a delivery
The mailman should define delivery destinations

**Comment by MaabMohammedali** [comment]
The reciver will notify when the car outside

**Comment by Leililou** [comment]
This has nothing to do with the pick up, the user story is to notify the receiver before he delivery so that the receiver expects a delivery and waits for it
