### ISSUE TITLE
Environment simulation

### ISSUE THREAD

**Issue by guscuizi** [DIT112-V21/group-17#39]
- According to our plan, the car will work normally in the corridors of the building floors, and we need a more appropriate map for the car to run.
     Use Godot editor to create a new project to make mod
- Acceptance criteria:
     Build a map that fits the car operating scene and compatible with the original file

**Comment by platisd** [comment]
This is totally unfeasible at this point, please revise your plans.

**Comment by SvenHagenfors** [comment]
Our team have decided to scope out eviroment simulation because we are running out of time and we need to focus on what bring the most quality to the costumer.
