### ISSUE TITLE
Car Modes

### ISSUE THREAD

**Issue by sjoblads** [DIT112-V21/group-17#5]
**User story 2.2 : Car modes**
As a mail man I want to be able to choose an automatic mode so that the car delivers mails automatically.**

**Acceptance criteria:**  
The application should provide choices that allows the mailman to choose to control the car via auto-drive or manual drive.

**Comment by Leililou** [comment]
I updated the issue to follow the backlog that we have created.

**Comment by Leililou** [comment]
This issue is out of scope, we are only using manual mode because of lack of time
