### ISSUE TITLE
Android app UI 

### ISSUE THREAD

**Issue by Eliflili** [DIT112-V21/group-17#53]
As a user, I want a good interface so I can use the system easily without getting confused.
Acceptance criteria:
UI looks clear and simple to use and understandable code.

**Comment by Eliflili** [comment]
Well in the beginning we would create just login layout for different users (Receiver and mail man) but while we working we got to change some part of our project and we decide to work on the whole UI so to make all screens slimier as one app.

**Comment by Eliflili** [comment]
> The acceptance criteria seem very vague in the context of the title of this issue, will this issue create the whole app UI or will it only include the login screen? Try to be more clear on what will be actually implemented.

Well in the beginning we would create just login layout for different users (Receiver and mail man) but while we working we got to change some part of our project and we decide to work on the whole UI so to make all screens slimier as one app.

**Comment by Eliflili** [comment]
I updated the UI layout, so I will reopen this issue

**Comment by Leililou** [comment]
This issue was linked to the PR of MqTT connection by mistake.
