### ISSUE TITLE
Log-in 

### ISSUE THREAD

**Issue by sjoblads** [DIT112-V21/group-17#7]
**As a user I want to be able to log in to the application so that I get access to my own account.**

- Acceptance criteria:  When the user inputs their correct password and username it should direct them to their personal account.

**Comment by Leililou** [comment]
I linked the issue to the PR

**Comment by Leililou** [comment]
this issue was started to be implemented (android side) but not finished and now is out of scope, due to lack of time and also because it's not a priority
